### ISSUE TITLE
Missing *.jar file in archive

### ISSUE THREAD

**Issue by mdziczkowski** [bobintetley/asm2#1]
Hello. I wanted to let you know that in the archive that should contain the java version of ASM are (except the sql and README files) only index.html and a httpdb.cgi files and the main *.jar file is not there.

I had choosen it because the ASM3 doesn't contain java version and the python3 one doesn't work by me due missing dependencies on Ubuntu 20.04 (focal) of with most got removed from the official ubuntu repositories for this Ubuntu version.

Could You try to find a fix for it ? Thanks

**Comment by bobintetley** [comment]
It expects you to use the jar file from one of the other builds, such as the "Linux/Unix" download.

**Comment by bobintetley** [comment]
Also, these are not development issues, please do not raise support issues as development. Use the forum at https://sheltermanager.com/site/en_forum.html
